/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RelationshipsRouteImport } from './routes/relationships'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as MarriageRouteImport } from './routes/marriage'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhatHappensSlugRouteImport } from './routes/what-happens.$slug'
import { Route as UPseudonymRouteImport } from './routes/u.$pseudonym'
import { Route as IsItNormalSlugRouteImport } from './routes/is-it-normal.$slug'
import { Route as ApiCompleteRouteImport } from './routes/api/complete'
import { Route as ApiFeedbackEventsRouteImport } from './routes/api/feedback/events'
import { Route as AuthenticatedCheckinIdRouteImport } from './routes/_authenticated/checkin.$id'
import { Route as HallsHallRegionWindowRouteImport } from './routes/halls.$hall.$region.$window'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksDispatchCheckinsRouteImport } from './routes/api/public/hooks/dispatch-checkins'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipsRoute = RelationshipsRouteImport.update({
  id: '/relationships',
  path: '/relationships',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const MarriageRoute = MarriageRouteImport.update({
  id: '/marriage',
  path: '/marriage',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatHappensSlugRoute = WhatHappensSlugRouteImport.update({
  id: '/what-happens/$slug',
  path: '/what-happens/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UPseudonymRoute = UPseudonymRouteImport.update({
  id: '/u/$pseudonym',
  path: '/u/$pseudonym',
  getParentRoute: () => rootRouteImport,
} as any)
const IsItNormalSlugRoute = IsItNormalSlugRouteImport.update({
  id: '/is-it-normal/$slug',
  path: '/is-it-normal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompleteRoute = ApiCompleteRouteImport.update({
  id: '/api/complete',
  path: '/api/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackEventsRoute = ApiFeedbackEventsRouteImport.update({
  id: '/api/feedback/events',
  path: '/api/feedback/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckinIdRoute = AuthenticatedCheckinIdRouteImport.update({
  id: '/checkin/$id',
  path: '/checkin/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const HallsHallRegionWindowRoute = HallsHallRegionWindowRouteImport.update({
  id: '/halls/$hall/$region/$window',
  path: '/halls/$hall/$region/$window',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchCheckinsRoute =
  ApiPublicHooksDispatchCheckinsRouteImport.update({
    id: '/api/public/hooks/dispatch-checkins',
    path: '/api/public/hooks/dispatch-checkins',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/family': typeof FamilyRoute
  '/marriage': typeof MarriageRoute
  '/methodology': typeof MethodologyRoute
  '/relationships': typeof RelationshipsRoute
  '/report': typeof ReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/api/complete': typeof ApiCompleteRoute
  '/is-it-normal/$slug': typeof IsItNormalSlugRoute
  '/u/$pseudonym': typeof UPseudonymRoute
  '/what-happens/$slug': typeof WhatHappensSlugRoute
  '/checkin/$id': typeof AuthenticatedCheckinIdRoute
  '/api/feedback/events': typeof ApiFeedbackEventsRoute
  '/api/public/hooks/dispatch-checkins': typeof ApiPublicHooksDispatchCheckinsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/halls/$hall/$region/$window': typeof HallsHallRegionWindowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/family': typeof FamilyRoute
  '/marriage': typeof MarriageRoute
  '/methodology': typeof MethodologyRoute
  '/relationships': typeof RelationshipsRoute
  '/report': typeof ReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/api/complete': typeof ApiCompleteRoute
  '/is-it-normal/$slug': typeof IsItNormalSlugRoute
  '/u/$pseudonym': typeof UPseudonymRoute
  '/what-happens/$slug': typeof WhatHappensSlugRoute
  '/checkin/$id': typeof AuthenticatedCheckinIdRoute
  '/api/feedback/events': typeof ApiFeedbackEventsRoute
  '/api/public/hooks/dispatch-checkins': typeof ApiPublicHooksDispatchCheckinsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/halls/$hall/$region/$window': typeof HallsHallRegionWindowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/family': typeof FamilyRoute
  '/marriage': typeof MarriageRoute
  '/methodology': typeof MethodologyRoute
  '/relationships': typeof RelationshipsRoute
  '/report': typeof ReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/api/complete': typeof ApiCompleteRoute
  '/is-it-normal/$slug': typeof IsItNormalSlugRoute
  '/u/$pseudonym': typeof UPseudonymRoute
  '/what-happens/$slug': typeof WhatHappensSlugRoute
  '/_authenticated/checkin/$id': typeof AuthenticatedCheckinIdRoute
  '/api/feedback/events': typeof ApiFeedbackEventsRoute
  '/api/public/hooks/dispatch-checkins': typeof ApiPublicHooksDispatchCheckinsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/halls/$hall/$region/$window': typeof HallsHallRegionWindowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/career'
    | '/family'
    | '/marriage'
    | '/methodology'
    | '/relationships'
    | '/report'
    | '/sitemap.xml'
    | '/trust'
    | '/api/complete'
    | '/is-it-normal/$slug'
    | '/u/$pseudonym'
    | '/what-happens/$slug'
    | '/checkin/$id'
    | '/api/feedback/events'
    | '/api/public/hooks/dispatch-checkins'
    | '/api/public/payments/webhook'
    | '/halls/$hall/$region/$window'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/career'
    | '/family'
    | '/marriage'
    | '/methodology'
    | '/relationships'
    | '/report'
    | '/sitemap.xml'
    | '/trust'
    | '/api/complete'
    | '/is-it-normal/$slug'
    | '/u/$pseudonym'
    | '/what-happens/$slug'
    | '/checkin/$id'
    | '/api/feedback/events'
    | '/api/public/hooks/dispatch-checkins'
    | '/api/public/payments/webhook'
    | '/halls/$hall/$region/$window'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$'
    | '/about'
    | '/career'
    | '/family'
    | '/marriage'
    | '/methodology'
    | '/relationships'
    | '/report'
    | '/sitemap.xml'
    | '/trust'
    | '/api/complete'
    | '/is-it-normal/$slug'
    | '/u/$pseudonym'
    | '/what-happens/$slug'
    | '/_authenticated/checkin/$id'
    | '/api/feedback/events'
    | '/api/public/hooks/dispatch-checkins'
    | '/api/public/payments/webhook'
    | '/halls/$hall/$region/$window'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  CareerRoute: typeof CareerRoute
  FamilyRoute: typeof FamilyRoute
  MarriageRoute: typeof MarriageRoute
  MethodologyRoute: typeof MethodologyRoute
  RelationshipsRoute: typeof RelationshipsRoute
  ReportRoute: typeof ReportRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrustRoute: typeof TrustRoute
  ApiCompleteRoute: typeof ApiCompleteRoute
  IsItNormalSlugRoute: typeof IsItNormalSlugRoute
  UPseudonymRoute: typeof UPseudonymRoute
  WhatHappensSlugRoute: typeof WhatHappensSlugRoute
  ApiFeedbackEventsRoute: typeof ApiFeedbackEventsRoute
  ApiPublicHooksDispatchCheckinsRoute: typeof ApiPublicHooksDispatchCheckinsRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  HallsHallRegionWindowRoute: typeof HallsHallRegionWindowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationships': {
      id: '/relationships'
      path: '/relationships'
      fullPath: '/relationships'
      preLoaderRoute: typeof RelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marriage': {
      id: '/marriage'
      path: '/marriage'
      fullPath: '/marriage'
      preLoaderRoute: typeof MarriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-happens/$slug': {
      id: '/what-happens/$slug'
      path: '/what-happens/$slug'
      fullPath: '/what-happens/$slug'
      preLoaderRoute: typeof WhatHappensSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$pseudonym': {
      id: '/u/$pseudonym'
      path: '/u/$pseudonym'
      fullPath: '/u/$pseudonym'
      preLoaderRoute: typeof UPseudonymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/is-it-normal/$slug': {
      id: '/is-it-normal/$slug'
      path: '/is-it-normal/$slug'
      fullPath: '/is-it-normal/$slug'
      preLoaderRoute: typeof IsItNormalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/complete': {
      id: '/api/complete'
      path: '/api/complete'
      fullPath: '/api/complete'
      preLoaderRoute: typeof ApiCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback/events': {
      id: '/api/feedback/events'
      path: '/api/feedback/events'
      fullPath: '/api/feedback/events'
      preLoaderRoute: typeof ApiFeedbackEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkin/$id': {
      id: '/_authenticated/checkin/$id'
      path: '/checkin/$id'
      fullPath: '/checkin/$id'
      preLoaderRoute: typeof AuthenticatedCheckinIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/halls/$hall/$region/$window': {
      id: '/halls/$hall/$region/$window'
      path: '/halls/$hall/$region/$window'
      fullPath: '/halls/$hall/$region/$window'
      preLoaderRoute: typeof HallsHallRegionWindowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-checkins': {
      id: '/api/public/hooks/dispatch-checkins'
      path: '/api/public/hooks/dispatch-checkins'
      fullPath: '/api/public/hooks/dispatch-checkins'
      preLoaderRoute: typeof ApiPublicHooksDispatchCheckinsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCheckinIdRoute: typeof AuthenticatedCheckinIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCheckinIdRoute: AuthenticatedCheckinIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  CareerRoute: CareerRoute,
  FamilyRoute: FamilyRoute,
  MarriageRoute: MarriageRoute,
  MethodologyRoute: MethodologyRoute,
  RelationshipsRoute: RelationshipsRoute,
  ReportRoute: ReportRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrustRoute: TrustRoute,
  ApiCompleteRoute: ApiCompleteRoute,
  IsItNormalSlugRoute: IsItNormalSlugRoute,
  UPseudonymRoute: UPseudonymRoute,
  WhatHappensSlugRoute: WhatHappensSlugRoute,
  ApiFeedbackEventsRoute: ApiFeedbackEventsRoute,
  ApiPublicHooksDispatchCheckinsRoute: ApiPublicHooksDispatchCheckinsRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  HallsHallRegionWindowRoute: HallsHallRegionWindowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
