/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as StreamRouteImport } from './routes/stream'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as RoomRouteImport } from './routes/room'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RelationshipsRouteImport } from './routes/relationships'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MirrorRouteImport } from './routes/mirror'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MarriageRouteImport } from './routes/marriage'
import { Route as LivedIntelligenceRouteImport } from './routes/lived-intelligence'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HallsRouteImport } from './routes/halls'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AiDisclosureRouteImport } from './routes/ai-disclosure'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhatHappensSlugRouteImport } from './routes/what-happens.$slug'
import { Route as UPseudonymRouteImport } from './routes/u.$pseudonym'
import { Route as SubscribeReturnRouteImport } from './routes/subscribe.return'
import { Route as SitemapsProfilesDotxmlRouteImport } from './routes/sitemaps/profiles[.]xml'
import { Route as SitemapsOutcomesDotxmlRouteImport } from './routes/sitemaps/outcomes[.]xml'
import { Route as SitemapsCoreDotxmlRouteImport } from './routes/sitemaps/core[.]xml'
import { Route as IsItNormalSlugRouteImport } from './routes/is-it-normal.$slug'
import { Route as ApiCompleteRouteImport } from './routes/api/complete'
import { Route as AdminRelateQueueRouteImport } from './routes/admin.relate-queue'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiFeedbackEventsRouteImport } from './routes/api/feedback/events'
import { Route as AuthenticatedCheckinIdRouteImport } from './routes/_authenticated/checkin.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as HallsHallRegionWindowRouteImport } from './routes/halls.$hall.$region.$window'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksReengagementEmailsRouteImport } from './routes/api/public/hooks/reengagement-emails'
import { Route as ApiPublicHooksMirrorEvolutionRouteImport } from './routes/api/public/hooks/mirror-evolution'
import { Route as ApiPublicHooksDispatchCheckinsRouteImport } from './routes/api/public/hooks/dispatch-checkins'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamRoute = StreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoute = RoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipsRoute = RelationshipsRouteImport.update({
  id: '/relationships',
  path: '/relationships',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MirrorRoute = MirrorRouteImport.update({
  id: '/mirror',
  path: '/mirror',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MarriageRoute = MarriageRouteImport.update({
  id: '/marriage',
  path: '/marriage',
  getParentRoute: () => rootRouteImport,
} as any)
const LivedIntelligenceRoute = LivedIntelligenceRouteImport.update({
  id: '/lived-intelligence',
  path: '/lived-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HallsRoute = HallsRouteImport.update({
  id: '/halls',
  path: '/halls',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDisclosureRoute = AiDisclosureRouteImport.update({
  id: '/ai-disclosure',
  path: '/ai-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatHappensSlugRoute = WhatHappensSlugRouteImport.update({
  id: '/what-happens/$slug',
  path: '/what-happens/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UPseudonymRoute = UPseudonymRouteImport.update({
  id: '/u/$pseudonym',
  path: '/u/$pseudonym',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeReturnRoute = SubscribeReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => SubscribeRoute,
} as any)
const SitemapsProfilesDotxmlRoute = SitemapsProfilesDotxmlRouteImport.update({
  id: '/sitemaps/profiles.xml',
  path: '/sitemaps/profiles.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapsOutcomesDotxmlRoute = SitemapsOutcomesDotxmlRouteImport.update({
  id: '/sitemaps/outcomes.xml',
  path: '/sitemaps/outcomes.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapsCoreDotxmlRoute = SitemapsCoreDotxmlRouteImport.update({
  id: '/sitemaps/core.xml',
  path: '/sitemaps/core.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IsItNormalSlugRoute = IsItNormalSlugRouteImport.update({
  id: '/is-it-normal/$slug',
  path: '/is-it-normal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompleteRoute = ApiCompleteRouteImport.update({
  id: '/api/complete',
  path: '/api/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRelateQueueRoute = AdminRelateQueueRouteImport.update({
  id: '/relate-queue',
  path: '/relate-queue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFeedbackEventsRoute = ApiFeedbackEventsRouteImport.update({
  id: '/api/feedback/events',
  path: '/api/feedback/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckinIdRoute = AuthenticatedCheckinIdRouteImport.update({
  id: '/checkin/$id',
  path: '/checkin/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/admin/events',
    path: '/admin/events',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const HallsHallRegionWindowRoute = HallsHallRegionWindowRouteImport.update({
  id: '/$hall/$region/$window',
  path: '/$hall/$region/$window',
  getParentRoute: () => HallsRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReengagementEmailsRoute =
  ApiPublicHooksReengagementEmailsRouteImport.update({
    id: '/api/public/hooks/reengagement-emails',
    path: '/api/public/hooks/reengagement-emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMirrorEvolutionRoute =
  ApiPublicHooksMirrorEvolutionRouteImport.update({
    id: '/api/public/hooks/mirror-evolution',
    path: '/api/public/hooks/mirror-evolution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchCheckinsRoute =
  ApiPublicHooksDispatchCheckinsRouteImport.update({
    id: '/api/public/hooks/dispatch-checkins',
    path: '/api/public/hooks/dispatch-checkins',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-disclosure': typeof AiDisclosureRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/family': typeof FamilyRoute
  '/faq': typeof FaqRoute
  '/guidelines': typeof GuidelinesRoute
  '/halls': typeof HallsRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/legal': typeof LegalRoute
  '/lived-intelligence': typeof LivedIntelligenceRoute
  '/marriage': typeof MarriageRoute
  '/mcp': typeof McpRoute
  '/methodology': typeof MethodologyRoute
  '/mirror': typeof MirrorRoute
  '/privacy': typeof PrivacyRoute
  '/relationships': typeof RelationshipsRoute
  '/report': typeof ReportRoute
  '/room': typeof RoomRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stream': typeof StreamRoute
  '/subscribe': typeof SubscribeRouteWithChildren
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/relate-queue': typeof AdminRelateQueueRoute
  '/api/complete': typeof ApiCompleteRoute
  '/is-it-normal/$slug': typeof IsItNormalSlugRoute
  '/sitemaps/core.xml': typeof SitemapsCoreDotxmlRoute
  '/sitemaps/outcomes.xml': typeof SitemapsOutcomesDotxmlRoute
  '/sitemaps/profiles.xml': typeof SitemapsProfilesDotxmlRoute
  '/subscribe/return': typeof SubscribeReturnRoute
  '/u/$pseudonym': typeof UPseudonymRoute
  '/what-happens/$slug': typeof WhatHappensSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/checkin/$id': typeof AuthenticatedCheckinIdRoute
  '/api/feedback/events': typeof ApiFeedbackEventsRoute
  '/api/public/hooks/dispatch-checkins': typeof ApiPublicHooksDispatchCheckinsRoute
  '/api/public/hooks/mirror-evolution': typeof ApiPublicHooksMirrorEvolutionRoute
  '/api/public/hooks/reengagement-emails': typeof ApiPublicHooksReengagementEmailsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/halls/$hall/$region/$window': typeof HallsHallRegionWindowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-disclosure': typeof AiDisclosureRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/family': typeof FamilyRoute
  '/faq': typeof FaqRoute
  '/guidelines': typeof GuidelinesRoute
  '/halls': typeof HallsRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/legal': typeof LegalRoute
  '/lived-intelligence': typeof LivedIntelligenceRoute
  '/marriage': typeof MarriageRoute
  '/mcp': typeof McpRoute
  '/methodology': typeof MethodologyRoute
  '/mirror': typeof MirrorRoute
  '/privacy': typeof PrivacyRoute
  '/relationships': typeof RelationshipsRoute
  '/report': typeof ReportRoute
  '/room': typeof RoomRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stream': typeof StreamRoute
  '/subscribe': typeof SubscribeRouteWithChildren
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/relate-queue': typeof AdminRelateQueueRoute
  '/api/complete': typeof ApiCompleteRoute
  '/is-it-normal/$slug': typeof IsItNormalSlugRoute
  '/sitemaps/core.xml': typeof SitemapsCoreDotxmlRoute
  '/sitemaps/outcomes.xml': typeof SitemapsOutcomesDotxmlRoute
  '/sitemaps/profiles.xml': typeof SitemapsProfilesDotxmlRoute
  '/subscribe/return': typeof SubscribeReturnRoute
  '/u/$pseudonym': typeof UPseudonymRoute
  '/what-happens/$slug': typeof WhatHappensSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/checkin/$id': typeof AuthenticatedCheckinIdRoute
  '/api/feedback/events': typeof ApiFeedbackEventsRoute
  '/api/public/hooks/dispatch-checkins': typeof ApiPublicHooksDispatchCheckinsRoute
  '/api/public/hooks/mirror-evolution': typeof ApiPublicHooksMirrorEvolutionRoute
  '/api/public/hooks/reengagement-emails': typeof ApiPublicHooksReengagementEmailsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/halls/$hall/$region/$window': typeof HallsHallRegionWindowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-disclosure': typeof AiDisclosureRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/family': typeof FamilyRoute
  '/faq': typeof FaqRoute
  '/guidelines': typeof GuidelinesRoute
  '/halls': typeof HallsRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/legal': typeof LegalRoute
  '/lived-intelligence': typeof LivedIntelligenceRoute
  '/marriage': typeof MarriageRoute
  '/mcp': typeof McpRoute
  '/methodology': typeof MethodologyRoute
  '/mirror': typeof MirrorRoute
  '/privacy': typeof PrivacyRoute
  '/relationships': typeof RelationshipsRoute
  '/report': typeof ReportRoute
  '/room': typeof RoomRoute
  '/safety': typeof SafetyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stream': typeof StreamRoute
  '/subscribe': typeof SubscribeRouteWithChildren
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/relate-queue': typeof AdminRelateQueueRoute
  '/api/complete': typeof ApiCompleteRoute
  '/is-it-normal/$slug': typeof IsItNormalSlugRoute
  '/sitemaps/core.xml': typeof SitemapsCoreDotxmlRoute
  '/sitemaps/outcomes.xml': typeof SitemapsOutcomesDotxmlRoute
  '/sitemaps/profiles.xml': typeof SitemapsProfilesDotxmlRoute
  '/subscribe/return': typeof SubscribeReturnRoute
  '/u/$pseudonym': typeof UPseudonymRoute
  '/what-happens/$slug': typeof WhatHappensSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/checkin/$id': typeof AuthenticatedCheckinIdRoute
  '/api/feedback/events': typeof ApiFeedbackEventsRoute
  '/api/public/hooks/dispatch-checkins': typeof ApiPublicHooksDispatchCheckinsRoute
  '/api/public/hooks/mirror-evolution': typeof ApiPublicHooksMirrorEvolutionRoute
  '/api/public/hooks/reengagement-emails': typeof ApiPublicHooksReengagementEmailsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/halls/$hall/$region/$window': typeof HallsHallRegionWindowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/ai-disclosure'
    | '/career'
    | '/contact'
    | '/family'
    | '/faq'
    | '/guidelines'
    | '/halls'
    | '/how-it-works'
    | '/legal'
    | '/lived-intelligence'
    | '/marriage'
    | '/mcp'
    | '/methodology'
    | '/mirror'
    | '/privacy'
    | '/relationships'
    | '/report'
    | '/room'
    | '/safety'
    | '/sitemap.xml'
    | '/stream'
    | '/subscribe'
    | '/terms'
    | '/trust'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/profile'
    | '/admin/feedback'
    | '/admin/relate-queue'
    | '/api/complete'
    | '/is-it-normal/$slug'
    | '/sitemaps/core.xml'
    | '/sitemaps/outcomes.xml'
    | '/sitemaps/profiles.xml'
    | '/subscribe/return'
    | '/u/$pseudonym'
    | '/what-happens/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/analytics'
    | '/admin/events'
    | '/admin/users'
    | '/checkin/$id'
    | '/api/feedback/events'
    | '/api/public/hooks/dispatch-checkins'
    | '/api/public/hooks/mirror-evolution'
    | '/api/public/hooks/reengagement-emails'
    | '/api/public/payments/webhook'
    | '/halls/$hall/$region/$window'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/ai-disclosure'
    | '/career'
    | '/contact'
    | '/family'
    | '/faq'
    | '/guidelines'
    | '/halls'
    | '/how-it-works'
    | '/legal'
    | '/lived-intelligence'
    | '/marriage'
    | '/mcp'
    | '/methodology'
    | '/mirror'
    | '/privacy'
    | '/relationships'
    | '/report'
    | '/room'
    | '/safety'
    | '/sitemap.xml'
    | '/stream'
    | '/subscribe'
    | '/terms'
    | '/trust'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/profile'
    | '/admin/feedback'
    | '/admin/relate-queue'
    | '/api/complete'
    | '/is-it-normal/$slug'
    | '/sitemaps/core.xml'
    | '/sitemaps/outcomes.xml'
    | '/sitemaps/profiles.xml'
    | '/subscribe/return'
    | '/u/$pseudonym'
    | '/what-happens/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/analytics'
    | '/admin/events'
    | '/admin/users'
    | '/checkin/$id'
    | '/api/feedback/events'
    | '/api/public/hooks/dispatch-checkins'
    | '/api/public/hooks/mirror-evolution'
    | '/api/public/hooks/reengagement-emails'
    | '/api/public/payments/webhook'
    | '/halls/$hall/$region/$window'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$'
    | '/about'
    | '/admin'
    | '/ai-disclosure'
    | '/career'
    | '/contact'
    | '/family'
    | '/faq'
    | '/guidelines'
    | '/halls'
    | '/how-it-works'
    | '/legal'
    | '/lived-intelligence'
    | '/marriage'
    | '/mcp'
    | '/methodology'
    | '/mirror'
    | '/privacy'
    | '/relationships'
    | '/report'
    | '/room'
    | '/safety'
    | '/sitemap.xml'
    | '/stream'
    | '/subscribe'
    | '/terms'
    | '/trust'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/profile'
    | '/admin/feedback'
    | '/admin/relate-queue'
    | '/api/complete'
    | '/is-it-normal/$slug'
    | '/sitemaps/core.xml'
    | '/sitemaps/outcomes.xml'
    | '/sitemaps/profiles.xml'
    | '/subscribe/return'
    | '/u/$pseudonym'
    | '/what-happens/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/users'
    | '/_authenticated/checkin/$id'
    | '/api/feedback/events'
    | '/api/public/hooks/dispatch-checkins'
    | '/api/public/hooks/mirror-evolution'
    | '/api/public/hooks/reengagement-emails'
    | '/api/public/payments/webhook'
    | '/halls/$hall/$region/$window'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiDisclosureRoute: typeof AiDisclosureRoute
  CareerRoute: typeof CareerRoute
  ContactRoute: typeof ContactRoute
  FamilyRoute: typeof FamilyRoute
  FaqRoute: typeof FaqRoute
  GuidelinesRoute: typeof GuidelinesRoute
  HallsRoute: typeof HallsRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  LegalRoute: typeof LegalRoute
  LivedIntelligenceRoute: typeof LivedIntelligenceRoute
  MarriageRoute: typeof MarriageRoute
  McpRoute: typeof McpRoute
  MethodologyRoute: typeof MethodologyRoute
  MirrorRoute: typeof MirrorRoute
  PrivacyRoute: typeof PrivacyRoute
  RelationshipsRoute: typeof RelationshipsRoute
  ReportRoute: typeof ReportRoute
  RoomRoute: typeof RoomRoute
  SafetyRoute: typeof SafetyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StreamRoute: typeof StreamRoute
  SubscribeRoute: typeof SubscribeRouteWithChildren
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  WelcomeRoute: typeof WelcomeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiCompleteRoute: typeof ApiCompleteRoute
  IsItNormalSlugRoute: typeof IsItNormalSlugRoute
  SitemapsCoreDotxmlRoute: typeof SitemapsCoreDotxmlRoute
  SitemapsOutcomesDotxmlRoute: typeof SitemapsOutcomesDotxmlRoute
  SitemapsProfilesDotxmlRoute: typeof SitemapsProfilesDotxmlRoute
  UPseudonymRoute: typeof UPseudonymRoute
  WhatHappensSlugRoute: typeof WhatHappensSlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiFeedbackEventsRoute: typeof ApiFeedbackEventsRoute
  ApiPublicHooksDispatchCheckinsRoute: typeof ApiPublicHooksDispatchCheckinsRoute
  ApiPublicHooksMirrorEvolutionRoute: typeof ApiPublicHooksMirrorEvolutionRoute
  ApiPublicHooksReengagementEmailsRoute: typeof ApiPublicHooksReengagementEmailsRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream': {
      id: '/stream'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof StreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room': {
      id: '/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationships': {
      id: '/relationships'
      path: '/relationships'
      fullPath: '/relationships'
      preLoaderRoute: typeof RelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mirror': {
      id: '/mirror'
      path: '/mirror'
      fullPath: '/mirror'
      preLoaderRoute: typeof MirrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marriage': {
      id: '/marriage'
      path: '/marriage'
      fullPath: '/marriage'
      preLoaderRoute: typeof MarriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lived-intelligence': {
      id: '/lived-intelligence'
      path: '/lived-intelligence'
      fullPath: '/lived-intelligence'
      preLoaderRoute: typeof LivedIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halls': {
      id: '/halls'
      path: '/halls'
      fullPath: '/halls'
      preLoaderRoute: typeof HallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-disclosure': {
      id: '/ai-disclosure'
      path: '/ai-disclosure'
      fullPath: '/ai-disclosure'
      preLoaderRoute: typeof AiDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-happens/$slug': {
      id: '/what-happens/$slug'
      path: '/what-happens/$slug'
      fullPath: '/what-happens/$slug'
      preLoaderRoute: typeof WhatHappensSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$pseudonym': {
      id: '/u/$pseudonym'
      path: '/u/$pseudonym'
      fullPath: '/u/$pseudonym'
      preLoaderRoute: typeof UPseudonymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe/return': {
      id: '/subscribe/return'
      path: '/return'
      fullPath: '/subscribe/return'
      preLoaderRoute: typeof SubscribeReturnRouteImport
      parentRoute: typeof SubscribeRoute
    }
    '/sitemaps/profiles.xml': {
      id: '/sitemaps/profiles.xml'
      path: '/sitemaps/profiles.xml'
      fullPath: '/sitemaps/profiles.xml'
      preLoaderRoute: typeof SitemapsProfilesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/outcomes.xml': {
      id: '/sitemaps/outcomes.xml'
      path: '/sitemaps/outcomes.xml'
      fullPath: '/sitemaps/outcomes.xml'
      preLoaderRoute: typeof SitemapsOutcomesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/core.xml': {
      id: '/sitemaps/core.xml'
      path: '/sitemaps/core.xml'
      fullPath: '/sitemaps/core.xml'
      preLoaderRoute: typeof SitemapsCoreDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/is-it-normal/$slug': {
      id: '/is-it-normal/$slug'
      path: '/is-it-normal/$slug'
      fullPath: '/is-it-normal/$slug'
      preLoaderRoute: typeof IsItNormalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/complete': {
      id: '/api/complete'
      path: '/api/complete'
      fullPath: '/api/complete'
      preLoaderRoute: typeof ApiCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/relate-queue': {
      id: '/admin/relate-queue'
      path: '/relate-queue'
      fullPath: '/admin/relate-queue'
      preLoaderRoute: typeof AdminRelateQueueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback/events': {
      id: '/api/feedback/events'
      path: '/api/feedback/events'
      fullPath: '/api/feedback/events'
      preLoaderRoute: typeof ApiFeedbackEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkin/$id': {
      id: '/_authenticated/checkin/$id'
      path: '/checkin/$id'
      fullPath: '/checkin/$id'
      preLoaderRoute: typeof AuthenticatedCheckinIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halls/$hall/$region/$window': {
      id: '/halls/$hall/$region/$window'
      path: '/$hall/$region/$window'
      fullPath: '/halls/$hall/$region/$window'
      preLoaderRoute: typeof HallsHallRegionWindowRouteImport
      parentRoute: typeof HallsRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reengagement-emails': {
      id: '/api/public/hooks/reengagement-emails'
      path: '/api/public/hooks/reengagement-emails'
      fullPath: '/api/public/hooks/reengagement-emails'
      preLoaderRoute: typeof ApiPublicHooksReengagementEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mirror-evolution': {
      id: '/api/public/hooks/mirror-evolution'
      path: '/api/public/hooks/mirror-evolution'
      fullPath: '/api/public/hooks/mirror-evolution'
      preLoaderRoute: typeof ApiPublicHooksMirrorEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-checkins': {
      id: '/api/public/hooks/dispatch-checkins'
      path: '/api/public/hooks/dispatch-checkins'
      fullPath: '/api/public/hooks/dispatch-checkins'
      preLoaderRoute: typeof ApiPublicHooksDispatchCheckinsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedCheckinIdRoute: typeof AuthenticatedCheckinIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedCheckinIdRoute: AuthenticatedCheckinIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminRelateQueueRoute: typeof AdminRelateQueueRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminRelateQueueRoute: AdminRelateQueueRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HallsRouteChildren {
  HallsHallRegionWindowRoute: typeof HallsHallRegionWindowRoute
}

const HallsRouteChildren: HallsRouteChildren = {
  HallsHallRegionWindowRoute: HallsHallRegionWindowRoute,
}

const HallsRouteWithChildren = HallsRoute._addFileChildren(HallsRouteChildren)

interface SubscribeRouteChildren {
  SubscribeReturnRoute: typeof SubscribeReturnRoute
}

const SubscribeRouteChildren: SubscribeRouteChildren = {
  SubscribeReturnRoute: SubscribeReturnRoute,
}

const SubscribeRouteWithChildren = SubscribeRoute._addFileChildren(
  SubscribeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AiDisclosureRoute: AiDisclosureRoute,
  CareerRoute: CareerRoute,
  ContactRoute: ContactRoute,
  FamilyRoute: FamilyRoute,
  FaqRoute: FaqRoute,
  GuidelinesRoute: GuidelinesRoute,
  HallsRoute: HallsRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  LegalRoute: LegalRoute,
  LivedIntelligenceRoute: LivedIntelligenceRoute,
  MarriageRoute: MarriageRoute,
  McpRoute: McpRoute,
  MethodologyRoute: MethodologyRoute,
  MirrorRoute: MirrorRoute,
  PrivacyRoute: PrivacyRoute,
  RelationshipsRoute: RelationshipsRoute,
  ReportRoute: ReportRoute,
  RoomRoute: RoomRoute,
  SafetyRoute: SafetyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StreamRoute: StreamRoute,
  SubscribeRoute: SubscribeRouteWithChildren,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  WelcomeRoute: WelcomeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiCompleteRoute: ApiCompleteRoute,
  IsItNormalSlugRoute: IsItNormalSlugRoute,
  SitemapsCoreDotxmlRoute: SitemapsCoreDotxmlRoute,
  SitemapsOutcomesDotxmlRoute: SitemapsOutcomesDotxmlRoute,
  SitemapsProfilesDotxmlRoute: SitemapsProfilesDotxmlRoute,
  UPseudonymRoute: UPseudonymRoute,
  WhatHappensSlugRoute: WhatHappensSlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiFeedbackEventsRoute: ApiFeedbackEventsRoute,
  ApiPublicHooksDispatchCheckinsRoute: ApiPublicHooksDispatchCheckinsRoute,
  ApiPublicHooksMirrorEvolutionRoute: ApiPublicHooksMirrorEvolutionRoute,
  ApiPublicHooksReengagementEmailsRoute: ApiPublicHooksReengagementEmailsRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
